# The bits of wire-server's docker-compose.yml we need. To not confuse our
# containers with that of wire-server, we use different ports.
networks:
  bloodhound_tests:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.7.0/24

services:
  elasticsearch_5:
    container_name: bloodhound_tests_elasticsearch_5
    build:
      context: .
      dockerfile_inline: |
        FROM quay.io/wire/elasticsearch:0.0.9-amd64
        RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack -b
        # this seems to be necessary to run X-Pack on Alpine (https://discuss.elastic.co/t/elasticsearch-failing-to-start-due-to-x-pack/85125/7)
        RUN rm -rf /usr/share/elasticsearch/plugins/x-pack/platform/linux-x86_64
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:7202:9200"
      - "127.0.0.1:7302:9300"
    environment:
      - "xpack.ml.enabled=false"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.ssl.certificate=certs/elasticsearch-cert.pem"
      - "xpack.ssl.key=certs/elasticsearch-key.pem"
      - "bootstrap.system_call_filter=false"
      - "JVM_OPTIONS_ES=-Xmx512m -Xms512m"
      - "discovery.type=single-node"
    volumes:
      - ./docker/elasticsearch-cert.pem:/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
      - ./docker/elasticsearch-key.pem:/usr/share/elasticsearch/config/certs/elasticsearch-key.pem
    networks:
      - bloodhound_tests

  elasticsearch_6:
    container_name: bloodhound_tests_elasticsearch_6
    image: elasticsearch:6.8.23
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:7200:9200"
      - "127.0.0.1:7300:9300"
    environment:
      - "xpack.ml.enabled=false"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.ssl.certificate=certs/elasticsearch-cert.pem"
      - "xpack.ssl.key=certs/elasticsearch-key.pem"
      - "bootstrap.system_call_filter=false"
      - "JVM_OPTIONS_ES=-Xmx512m -Xms512m"
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=changeme
    volumes:
      - ./docker/elasticsearch-cert.pem:/usr/share/elasticsearch/config/certs/elasticsearch-cert.pem
      - ./docker/elasticsearch-key.pem:/usr/share/elasticsearch/config/certs/elasticsearch-key.pem
    networks:
      - bloodhound_tests

  opensearch:
    container_name: bloodhound_tests_opensearch
    image: opensearchproject/opensearch:1.3.19
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:7201:9200"
      - "127.0.0.1:7301:9300"
    environment:
      - "bootstrap.system_call_filter=false"
      - "JVM_OPTIONS_ES=-Xmx512m -Xms512m"
      - "discovery.type=single-node"

      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ch4ng3m3Secr3t!"
    volumes:
      - ./docker/elasticsearch-cert.pem:/usr/share/opensearch/config/certs/tls.crt
      - ./docker/elasticsearch-key.pem:/usr/share/opensearch/config/certs/tls.key
      - ./docker/elasticsearch-ca.pem:/usr/share/opensearch/config/certs/ca.crt
      - ./docker/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./docker/opensearch/opensearch-security/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      - ./docker/opensearch/opensearch-security/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - ./docker/opensearch/opensearch-security/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      - ./docker/opensearch/opensearch-security/allowlist.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/allowlist.yml
      - ./docker/opensearch/opensearch-security/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      - ./docker/opensearch/opensearch-security/nodes_dn.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/nodes_dn.yml
      - ./docker/opensearch/opensearch-security/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
      - ./docker/opensearch/opensearch-security/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
    networks:
      - bloodhound_tests

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:1
    container_name: bloodhound_tests_opensearch-dashboards
    ports:
      - 7601:5601
    expose:
      - "7601"
    volumes:
      - ./docker/opensearch/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - bloodhound_tests
